name = "SarPy"
uuid = "86d99d7a-471f-4e3c-82f7-e4339723f0e6"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
